CREATE TABLE IF NOT EXISTS tblVideos(
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	Title TEXT NOT NULL DEFAULT 'Unavailable',
	Description TEXT NOT NULL DEFAULT 'Unavailable',
	DurationSeconds INTEGER,
	WebpageURL TEXT NOT NULL,
	PlaylistVideoIndex INTEGER,
	IsFileDownloaded INTEGER NOT NULL DEFAULT 0,
	ChannelId INTEGER,
	PlayListId INTEGER,
	LiveStatusId INTEGER,
	DomainId INTEGER,
	AvailabilityId INTEGER,
	FormatId INTEGER,	
	YoutubeVideoId INTEGER,
	IsDeleted INTEGER,
	CreatedDate INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS tblChannels(
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	Name TEXT NOT NULL DEFAULT 'Unavailable',
	ChannelURL TEXT,
	YoutubeChannelId INTEGER,
	CreatedDate INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS tblLiveStatusType(
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	LiveStatus TEXT
);

CREATE TABLE IF NOT EXISTS tblAvailabilityType(
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	Availability TEXT
);

CREATE TABLE IF NOT EXISTS tblPlaylist(
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	Title TEXT NOT NULL DEFAULT 'Unavailable',
	VideoCount INTEGER,
	Directory TEXT,
	ChannelId INTEGER,
	ThumbnailFileId INTEGER,
	YoutubePlaylistID INTEGER,
	CreatedDate INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS tblFormats(
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	Format TEXT,
	FormatNote TEXT,
	Resolution TEXT,
	StreamType TEXT,
	CreatedDate INTEGER
);

CREATE TABLE IF NOT EXISTS tblDomains(
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	Domain TEXT DEFAULT 'Unavailable',
	CreatedDate INTEGER
);

CREATE TABLE IF NOT EXISTS tblTags(
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	Name TEXT,
	IsUsed INTEGER NOT NULL DEFAULT 0,	
	CreatedDate INTEGER
);

CREATE TABLE IF NOT EXISTS tblVideoFileTags(
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	TagId INTEGER NOT NULL,
	VideoId INTEGER,
	FileId INTEGER,
	CreatedDate INTEGER
);

CREATE TABLE IF NOT EXISTS tblCategories(
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	Name TEXT,
	IsUsed INTEGER NOT NULL DEFAULT 0,	
	CreatedDate INTEGER
);

CREATE TABLE IF NOT EXISTS tblVideoFileCategories(
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	CategoryId INTEGER NOT NULL,
	VideoId INTEGER,
	FileId INTEGER,
	CreatedDate INTEGER
);

CREATE TABLE IF NOT EXISTS tblFiles(
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	VideoId INTEGER NOT NULL,
	FileTypeId INTEGER,
	SourceId INTEGER,
	FilePath TEXT,
	FileName TEXT,
	Extension TEXT,
	FileSize INTEGER,
	FileSizeUnit TEXT,
	NetworkPath TEXT,	
	IsDeleted INTEGER,
	CreatedDate INTEGER
);

CREATE TABLE IF NOT EXISTS tblSourceType(
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	Source TEXT
);

CREATE TABLE IF NOT EXISTS tblFileType(
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	File TEXT
);

--this is for some history the user may want
CREATE TABLE IF NOT EXISTS tblNetworkActivityLogs(
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	ActivityTypeId INTEGER NOT NULL,	
	InputURL TEXT,
	Command TEXT,
	Result TEXT,
	CreatedDate INTEGER
);

CREATE TABLE IF NOT EXISTS tblLocalActivityLogs(
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	ActivityTypeId INTEGER NOT NULL,	
	VideoId INTEGER,
	FileId INTEGER,
	Remarks TEXT,
	CreatedDate INTEGER
);

CREATE TABLE IF NOT EXISTS tblActivityType(
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	ActivityName TEXT,
	IsNetworkActivity INTEGER NOT NULL DEFAULT 0,
	IsActive INTEGER NOT NULL DEFAULT 1
);

--this is for debugging perf/errors
CREATE TABLE IF NOT EXISTS tblAPILogs(
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	APIName TEXT,
	ExecutionStart INTEGER,
	ExecutionEnd INTEGER,
	APIInputs TEXT,
	APIResult TEXT,
	ActivityLogId INTEGER,
	VideoId INTEGER,
	CreatedDate INTEGER
);

CREATE TABLE IF NOT EXISTS tblAPIType(
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	APIName TEXT,
	APIVersion TEXT NOT NULL DEFAULT 'v1',
	IsActive INTEGER NOT NULL DEFAULT 1
);